Bugfix: Add param positional arg to InvalidRequestError
I was testing some code and I got this error:
```
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 37, in class_url
    raise error.InvalidRequestError(
TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'
```

So I checked this file and saw that in a few cases, InvalidRequestError was missing the second positional argument `param`