Remove `python_bitness` check to prevent crash
Having an OpenAI, Celery, and NLTK setup, the check being removed generates a crash in the app:

```
[2024-07-18 19:02:07,828: ERROR/MainProcess] Process 'ForkPoolWorker-4' pid:30848 exited with 'signal 4 (SIGILL)'
[2024-07-18 19:02:07,848: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 4 (SIGILL) Job: 3.')
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback:
"""
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 4 (SIGILL) Job: 3.
"""
```